# This is a basic workflow to help you get started with Actions

name: Test

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '2.7.18'
      - uses: borales/actions-yarn@v2.3.0
      - run: yarn ganache -d > /dev/null &
      - run: yarn test
