name: Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
jobs:
  run_ci_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.0"

      - name: Install Yarn
        run: npm install -g yarn@1.22.19

      - name: Install packages
        run: yarn install

      - name: Setup local environment
        run: yarn run ganache & sleep 5

      - name: Run size check
        run: yarn run contract-size

      - name: Run tests
        run: yarn run test