name: Test

on: workflow_dispatch
jobs:
  run_ci_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.20.0"

      - name: Install Yarn
        run: npm install -g yarn@1.22.22

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install packages
        run: yarn install

      - name: Setup local environment
        run: cp config.js.example config.js && ./start-ganache.sh

      - name: Run static checks
        run: yarn static-check

      - name: Run size check
        run: yarn contract-size

      - name: Run tests
        run: yarn test